requirements:
  - requirements/tools.txt
      updates: all
      pin: True
  - requirements/test.txt
      updates: all
      pin: True
  - requirements/benchmark.txt
      updates: all
      pin: True
