language: ruby

sudo: false

cache:
    cargo: true
    directories:
        - $HOME/.rustup

install:
  - export PATH=$PATH:$HOME/.cargo/bin
  - scripts/ensure-rustup.sh
  - bundle install


jobs:
  include:
    - stage: test
      script: bundle exec rake format
    -
      script: bundle exec rake doc
    -
      script: ./scripts/run-tests-isolated.sh

before_deploy:
  script:
    - rake tag_release

deploy:
  provider: releases
  api_key:
    secure: wa05CldqVjYhPt031t+cvkKsMrlTsuEYFmGn5tp2aNUoJbYw5UNovZTqsPCZUbG8alU/u35I0Wzul/YMc8pRAC7N82E0ZCmZ4G+MAqjWMspT8pNHLh3VvPEEQnG7sgTaXWK2MViWeOOPICILUIzhMNFadNMk3I2fw4AJUG11uWS9nky/cIrsk3THPFZl6qWfcMr1U01OfCgF4r8Vv3TcF65YLkg9cHdVwiNlH1kI6turA0DP1SY57gat3nH45vR/+AVw2KivAFPzujCBlw3w6vzPGP+WNE8FNzg/CV0az5kyPo5qXC9f8yKQLOYJzzR8ZgCsmZkBwzq8rBs8yqZ3sXU14bSEtOOzUnKv+9fwDTm8B8MkYifZDhhPyxFf74h2cs75ZdlHSt8sK3HuBG8ZKDWlla2XqQo0UpzQLmPe9YO3lWPdL585bV80d8YIFQWP9h7rrbVkdNyjNU7oa8MUz7Ju26/dMI1LD6ytfonmSvPQngxRi+g0w/A/K7EFcZPbWLgNChLAYFxoYJLoSa+chcKPQ8+ckinvdt4gW9TT+nuCOpynoW/is4c6ruRKVC4e6dYFU98Qa5YWcnZW/ltWTKex0Bv48uEcuP/qbb9QtkfEHtrSIyIsJTwAZfiezi0mRV2zI1iHbayoHJkBlk4G95tFZoyOvSNwlfNFzXsS64A=
  file: hypothesis-*.gem
  file_glob: true
  on:
    repo: HypothesisWorks/hypothesis-ruby
    branch: master
