language: python

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

python:
  - pypy
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_script:
  - pip install pytest coverage
  - find . -name "*.pyc" -delete

script:
  - PYTHONPATH=src python -u -m coverage run -a --branch --include 'src/hypothesis/*' --omit 'src/hypothesis/settings.py,src/hypothesis/internal/compat.py,src/hypothesis/extra.py' $(which py.test) -v tests --ignore=tests/test_recursively.py
  - ./database-test.sh
  - coverage report -m --fail-under=100
  - PYTHONPATH=src py.test -v tests/test_recursively.py
  - pip install flake8 restructuredtext_lint pygments pyformat
  - find src tests hypothesis-extra/*/{src,tests} -name "*.py"
  - git diff --exit-code
  - flake8 src tests --exclude=compat.py,test_reflection.py --ignore=E731
  - ./installer-test.sh
  - ./extra-test.sh
