language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

os:
    - osx
    - linux

cache:
    apt: true
    directories:
        - $HOME/.pyenv
        - $HOME/.venv
        - $HOME/.cache/pip

env:
    matrix:
        - TOXENV=lint
        - TOXENV=pypy
        - TOXENV=pypy3
        - TOXENV=py27
        - TOXENV=py32
        - TOXENV=py33
        - TOXENV=py34

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

matrix:
    exclude:
        - os: osx
          env: TOXENV=lint
