language: ruby

sudo: false

cache:
    cargo: true
    directories:
        - $HOME/.rustup

install:
  - export PATH=$PATH:$HOME/.cargo/bin
  - scripts/ensure-rustup.sh
  - bundle install

branches:
  only:
    - "master"

env:
    matrix:
        - TASK=rubocop
        - TASK=test

script:
    - bundle exec rake $TASK
