language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install: python setup.py install

before_script:
  - pip install --use-mirrors pytest pytest-timeout flake8 coveralls

script:
  - coverage run --include hypothesis $(which py.test) -v hypothesis
  - flake8 hypothesis 
  - ./installer-test.sh

after_success:
    - coveralls
