language: python

python:
  - 2.7
  - 3.3
  - 3.4

install: python setup.py install

before_script:
  - pip install pytest pytest-timeout flake8 coverage

script:
  - python -u -m pytest -v hypothesis
  - python -u -m coverage run --branch --include 'hypothesis/*' $(which py.test) -v hypothesis
  - coverage report -m --fail-under=100
  - flake8 hypothesis 
  - ./installer-test.sh
