language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

os:
    - osx
    - linux

cache:
    apt: true
    directories:
        - $HOME/.pyenv
        - $HOME/.venv
        - $HOME/.cache/pip
        - $HOME/wheelhouse

env:
    matrix:
        - TOXENV=coverage
        - TOXENV=django17
        - TOXENV=django18
        - TOXENV=lint
        - TOXENV=examples2
        - TOXENV=examples3
        - TOXENV=pypy
        - TOXENV=py26
        - TOXENV=py34
        - TOXENV=py27
        - TOXENV=py33

install:
    - ./scripts/install.sh

script:
    - ./scripts/run.sh

matrix:
    exclude:
        - os: osx
          env: TOXENV=django17
        - os: osx
          env: TOXENV=django18
        - os: osx
          env: TOXENV=examples2
        - os: osx
          env: TOXENV=examples3
        - os: osx
          env: TOXENV=coverage
        - os: osx
          env: TOXENV=lint
