language: ruby

sudo: false

cache:
    apt: true
    directories:
        - $HOME/.cargo
        - $HOME/.rustup

install:
  - scripts/ensure-rustup.sh

branches:
  only:
    - "master"

env:
    matrix:
        # Core tests that we want to run first.
        - TASK=rubocop
        - TASK=test

script:
    - bundle exec rake $TASK
