language: c

env: PYTHONDONTWRITEBYTECODE=x

os:
    - osx
    - linux

cache:
    directories:
        - $HOME/.pyenv

env:
    matrix:
        - TOXENV=lint
        - TOXENV=pypy
        - TOXENV=py27
        - TOXENV=py32
        - TOXENV=py33
        - TOXENV=py34

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

matrix:
    exclude:
        - os: osx
          env: TOXENV=lint
