language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

install: python setup.py install

before_script:
  - pip install --use-mirrors pytest pytest-timeout flake8

script:
  - py.test -v hypothesis
  - flake8 hypothesis 
  - mkdir -p hypothesis-testing-chamber; cd hypothesis-testing-chamber; python -c 'from hypothesis import falsify; falsify(lambda x, y: x + y == y + x, str, str)'
