language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

os:
    - linux

before_install:
  - openssl aes-256-cbc -K $encrypted_39cb4cc39a80_key -iv $encrypted_39cb4cc39a80_iv -in deploy_key.enc -out deploy_key -d

branches:
  only:
    - "master"

cache:
    apt: true
    directories:
        - $HOME/.runtimes
        - $HOME/.venv
        - $HOME/.cache/pip
        - $HOME/wheelhouse

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes

    matrix:
        # Core tests that we want to run first.
        - TASK=check-untagged
        - TASK=check-changelog
        - TASK=documentation
        - TASK=lint
        - TASK=check-rst
        - TASK=check-format
        - TASK=check-coverage
        - TASK=check-pypy
        - TASK=check-py27
        - TASK=check-py36
        - TASK=check-quality

        # Less important tests that will probably
        # pass whenever the above do but are still
        # worth testing.
        - TASK=check-unicode
        - TASK=check-ancient-pip
        - TASK=check-py273
        - TASK=check-py34
        - TASK=check-py35
        - TASK=check-nose
        - TASK=check-pytest28
        - TASK=check-faker070
        - TASK=check-faker071
        - TASK=check-django18
        - TASK=check-django110
        - TASK=check-django111

script:
    - make $TASK

matrix:
    fast_finish: true

notifications:
  email:
    recipients:
      - david@drmaciver.com
    on_success: never
    on_failure: change

deploy:
  provider: pypi
  user: DRMacIver
  password:
    secure: T9tUyr9JG3KA8JprHUE8AAVaClUHHPHhiQRXC2/jHJv2EVEx2+EifkuR9sr5q1mCZ06g9v2+jhVNuaZyVuU9mmDKvJfADlPAagkCcgF/siuuJkzd3eIlELZHDtWPwKiZWCAD0Oj6yMdVB2w3/JTpJQhJx7HrL8EqbVdnN9YkMmI=
  on:
    branch: master
    repo: HypothesisWorks/hypothesis-python
    condition: make check-deploy-and-tag
