# https://aka.ms/yaml
variables:
  has_failure: False
  # Current tooling indexes directly into os.environ and will
  # fail without this defined
  # TODO: Implement specific PR logic and then fix up tooling to be okay
  # without this environment variable set
  travis_event_type: ''


jobs:
  - job: precheck
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        check-whole-repo-tests:
          TASK: check-whole-repo-tests
        lint:
          TASK: lint
        lint-ruby:
          TASK: lint-ruby
        check-format:
          TASK: check-format
        check-rust-tests:
          TASK: check-rust-tests
    condition: not(variables.has_failure)
    steps:
    - script: >
        sudo apt-get install
        libreadline-dev libsqlite3-dev
      displayName: Install apt dependencies
    - script: ./build.sh
      displayName: Run build tasks
    - script: echo '##vso[task.setvariable variable=has_failure]True'
      condition: failed()
      displayName: Set failure flag on failures

  - job: main
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        check-coverage:
          TASK: check-coverage
        check-pypy:
          TASK: check-pypy
        check-pypy3:
          TASK: check-pypy3
        check-py36:
          TASK: check-py36
        check-py27:
          TASK: check-py27
        # Python 3.4 doesn't build against libssl-dev on Azure, failing checks
        check-py34:
          TASK: check-py34
        check-py35:
          TASK: check-py35
        check-py37:
          TASK: check-py37
        check-quality:
          TASK: check-quality
        check-ruby-tests:
          TASK: check-ruby-tests
    condition: not(variables.has_failure)
    steps:
    - script: >
        sudo apt-get install
        libreadline-dev libsqlite3-dev
      displayName: Install apt dependencies
    - script: ./build.sh
      displayName: Run build tasks
    - script: echo '##vso[task.setvariable variable=has_failure]True'
      condition: failed()
      displayName: Set failure flag

  - job: extras
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        check-unicode:
          TASK: check-unicode
        check-py27-typing:
          TASK: check-py27-typing
        check-nose:
          TASK: check-nose
        check-pytest30:
          TASK: check-pytest30
        check-django21:
          TASK: check-django21
        check-django20:
          TASK: check-django20
        check-django111:
          TASK: check-django111
        check-pandas19:
          TASK: check-pandas19
        check-pandas22:
          TASK: check-pandas22
        check-pandas23:
          TASK: check-pandas23
        check-pandas24:
          TASK: check-pandas24
    condition: not(variables.has_failure)
    steps:
    - script: >
        sudo apt-get install
        libreadline-dev libsqlite3-dev
      displayName: Install apt dependencies
    - script: ./build.sh
      displayName: Run build tasks
    - script: echo '##vso[task.setvariable variable=has_failure]True'
      condition: failed()
      displayName: Set failure flag

# TODO: Deploy jobs dependent on above
